# Generated by Codex for the backend API migration.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('total_subtopicos', models.PositiveIntegerField(default=0)),
                ('subtopicos_concluidos', models.PositiveIntegerField(default=0)),
                ('progresso_cache', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('total_subtopicos', models.PositiveIntegerField(default=0)),
                ('subtopicos_concluidos', models.PositiveIntegerField(default=0)),
                ('progresso_cache', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='estudos.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('concluido', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='estudos.topico')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['usuario', 'nome'], name='estudos_cat_usuario_4ab6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='topico',
            index=models.Index(fields=['usuario', 'categoria', 'ordem'], name='estudos_top_usuario_5f1fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='subtopico',
            index=models.Index(fields=['topico', 'ordem'], name='estudos_sub_topico__055b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='subtopico',
            index=models.Index(fields=['concluido', 'concluido_em'], name='estudos_sub_conclui_375867_idx'),
        ),
    ]
