# Generated by Django 5.2.8 on 2026-06-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopico',
            name='subtopico_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos_filhos', to='estudos.subtopico'),
        ),
        migrations.AddIndex(
            model_name='subtopico',
            index=models.Index(fields=['topico', 'subtopico_pai', 'ordem'], name='estudos_sub_topico__145fe0_idx'),
        ),
    ]
